### ISSUE TITLE
Angular - Unable to get property 'apply' of undefined or null reference - IE11

### ISSUE THREAD

**Issue by brycekmartin** [aspnet/templating#90] opened 2017-10-24 18:40 UTC
I got the following error in the IE11 console from a fresh Angular 4 project.  
`SCRIPT5007: Unable to get property 'apply' of undefined or null reference
File: vendor.js, Line: 33893, Column: 5`

I saw this in another project I was developing and tried to come back to the base to see if it was something I introduced myself. 

Steps to reproduce: 
1) Create new .netcore 2.0 project
2) Select Angular template
3) Build/Run project
4) Open in IE 11 - You will need to open the developer tools and then refresh the page to see the error.

I tried adding a polyfill.ts in the other project I am working on with core-js shim imports but I get almost the same error but it points to Object.assign.

Any ideas?

**Comment by brycekmartin** [comment] 2017-10-30 17:55
Can anybody else validate if they have the same issues?  Thanks.

**Comment by brycekmartin** [comment] 2017-10-31 12:26
Found a fix for this over on the original aspnet/JavaScriptServices repo... See [PR 953](https://github.com/aspnet/JavaScriptServices/pull/953)

**Comment by SteveSandersonMS** [comment] 2017-11-07 21:42
Glad you found the fix, and apologies we didn't reply sooner! Closing this as a duplicate of the PR you linked to.

**Closed by SteveSandersonMS** 2017-11-07 21:42 UTC

**Comment by brycekmartin** [comment] 2017-11-10 15:35
Hey Steve, any idea when an updated version of the template might be release with some of the fixes that we've seen submitted?

**Comment by SteveSandersonMS** [comment] 2017-11-10 17:07
@brycekmartin We're hoping to have a preview release of the new Angular CLI and create-react-app based templates next month, with the final release following shortly after once the community has had a chance to try it out.

**Comment by brycekmartin** [comment] 2017-11-10 17:17
That is great.  I'll be watching closely. You guys are doing great.

**Comment by olivier-voutat** [comment] 2017-12-14 09:01
This fix works, but I'm experimenting some problems. We have an application with two components. A list of companies and a submit form.

The submit works (if we ignore a little problem with a input field with a placeholder with accents... that makes the "field is required" to be shown immediately).

But the list is not updated when we navigate. The webapi is not called on component opening. In Firefox it works as before. The web api is always called on component navigation.

Someone noticed that too and has a solution?

    ngOnInit(): void {
        let headers = new Headers({ 'Content-Type': 'application/json; charset=utf-8' });
        let options = new RequestOptions({ headers: headers });
        this.http.get('/api/firm/getlist', options).subscribe(response => {
            this.firms = response.json();
        });
    }
