### ISSUE TITLE
Avoid throwing 'ApplicationException' - it is not recommended by MSDN

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#29] opened 2017-09-22 18:19 UTC
_From @Eilon on August 8, 2017 19:49_

The `ApplicationException` has been essentially obsolete since .NET 1.0, and MSDN specifically recommends avoiding it:

https://msdn.microsoft.com/en-us/library/system.applicationexception(v=vs.110).aspx

> You should derive custom exceptions from the Exception class rather than the ApplicationException class. You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.

We should fix this ASAP in the project templates, as it is not a good practice.

_Copied from original issue: dotnet/templating#1191_

**Comment by DamianEdwards** [comment] 2017-10-06 17:49
Dupe of #9

**Closed by DamianEdwards** 2017-10-06 17:49 UTC
