### ISSUE TITLE
Angular template - Bootstrap

### ISSUE THREAD

**Issue by scottaddie** [aspnet/templating#510] opened 2018-05-04 20:16 UTC
Moved from https://github.com/aspnet/Docs/issues/6211. Originally posted by @kwakuduahc1 in regards to the Angular SPA template.

> There is a remarkable difference in the HTML markup for the nav-menu and any bootstrap template. As such, bootstrap files cannot be swapped to achieve same results. E.g. when you swap the bootstrap.min.css with any from bootswatch.com, the template jams quickly. It would be great the template could be made to comply with most others so that the template can be quickly swapped without tweaking here and there
> 
> Document Details
> ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.
> 
> ID: c047bdd1-1464-4398-92c6-65ab88093525
> Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
> Content: Use the Angular project template with ASP.NET Core
> Content Source: aspnetcore/spa/angular.md
> Service: unspecified
> GitHub Login: @SteveSandersonMS
> Microsoft Alias: scaddie

**Comment by mkArtakMSFT** [comment] 2018-05-17 04:29
@SteveSandersonMS, can you please provide some context here as it seems you're aware of the original issue.

**Comment by SteveSandersonMS** [comment] 2018-05-17 13:18
@mkArtakMSFT All I'd say is that the template's default nav menu is only an example, just like the default nav system in an ASP.NET MVC app is. We expect developers to replace/change it according to their needs. If there are specific suggestions (e.g., a PR) for how it should be changed we'd consider them.

**Comment by kwakuduahc1** [comment] 2018-05-19 03:52
Replacing or changing bootstrap.min.css or bootstrap.css appears to jam the whole nav menu. Even with the official bootstrap  release. Ideally, it is just supposed to work without modifying CSS or JavaScript. You will reach a stage where your only option is to accept the default nav menu.

To reproduce the problem, just start the angular template. Replace boostrap with any from bootswatch.com, the whole nav menu jams. Copy the HTML markup from bootswatch and replace with with the nav menu, that also does not work, which should actually work.

**Comment by mkArtakMSFT** [comment] 2018-05-21 17:09
Thanks for the details, folks.
This seems to be something custom, which we don't really intend to adapt as a default. Customizing a template means the developer takes full control over it. Closing this issue as there are no any plans to make dramatic improvements in this area to comply with custom styles.

**Closed by mkArtakMSFT** 2018-05-21 17:09 UTC
