### ISSUE TITLE
default ASP.NET Core template breaks when deployed in http only environment

### ISSUE THREAD

**Issue by tmds** [aspnet/templating#404] opened 2018-03-26 08:31 UTC
In microservice architecture it is common to use http (i.e. non https) services.

The default template includes HttpsRedirectionMiddleware.
When deploying this in a Docker container every request that is sent to the container, is responded with a redirect to a non-existing https port.

So the default template fails here (in production) for something that is (probably) an important use-case.

See https://github.com/aspnet/BasicMiddleware/issues/315 for some discussion on this topic.

**Comment by Eilon** [comment] 2018-03-26 18:07
@tmds - we're adding an option to create the templates without HTTPS enabled: https://github.com/aspnet/templating/issues/322

Would that solve your problem?

**Comment by tmds** [comment] 2018-03-26 22:04
That leaves the default template broken when you deploy it with http only. For services deployed using Kubernetes/OpenShift/haproxy/... this is a common deployment.

**Comment by leecow** [comment] 2018-03-30 22:07
Tom will the `--no-https` option added for Preview 2 (discussed in https://github.com/aspnet/templating/issues/322) enable this scenario?

**Comment by Eilon** [comment] 2018-04-05 17:33
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Comment by tmds** [comment] 2018-04-05 18:08
> @tmds , will the --no-https option added for Preview 2 (discussed in #322) enable this scenario satisfactorily?

@leecow That leaves the default template broken when you deploy it with http only. For services deployed using Kubernetes/OpenShift/haproxy/... this is a common deployment.

> Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

@Eilon do you have some info on why https has become the default? Do you think that is the most common deployment for ASP.NET Core apps?

**Comment by tmds** [comment] 2018-04-06 07:04
"secure by default" sounds good... how is it in practice:
During development, the developer certificate feature is nice since it gives an https experience.
In deployment, the actual certificate will commonly be placed on the server terminating SSL (IIS/haproxy/nginx/...).

This is also an issue for the dotnet-docker container. How do you intend to handle it there? Will the container have an untrusted developer certificate? Or is the container only meant to work behind a reverse proxy? Or should folks only use the --no-https template in containers?

Maybe we should make it possible to disable the HttpsRedirectionMiddleware using an environment variable?

**Comment by tmds** [comment] 2018-04-07 05:49
> This is also an issue for the dotnet-docker container. How do you intend to handle it there? Will the container have an untrusted developer certificate? Or is the container only meant to work behind a reverse proxy? Or should folks only use the --no-https template in containers?

@richlander @MichaelSimons do you know this?

**Comment by Eilon** [comment] 2018-04-08 00:12
@glennc / @DamianEdwards / @javiercn - should we have a further discussion on the HTTPS + Docker story?

**Comment by DamianEdwards** [comment] 2018-04-08 00:14
We had a discussion in the office yesterday and have a new plan to address this in RC. Basically the redirect middleware will no longer assume 443 if it can't otherwise determine the HTTPS endpoint address. We're also considering commenting out the HSTS middleware (or some other measure to avoid accidental application to unintended host names, e.g. localhost).

**Comment by javiercn** [comment] 2018-04-08 23:08
HSTS will not cause problems as only applies when the connection is HTTPS and it already has the ability to filter host names (to avoid applying it to localhost, etc.)

As for the redirection, let’s chat about it later this week.

**Comment by Eilon** [comment] 2018-04-09 19:25
I'll schedule a chat with: @DamianEdwards @davidfowl @javiercn @jbagga @mkArtakMSFT and me.

Need to figure out how we want to conditionally enable the HSTS middleware.

**Comment by jbagga** [comment] 2018-04-13 22:51
See  aspnet/BasicMiddleware#315 for further discussion. No changes are planned for the templates at the moment.

**Closed** 2018-04-14 00:02 UTC
Labels: 1 - Ready, discussion
