### ISSUE TITLE
VS2017 typescript breakpoints not working with the Angular Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0 template

### ISSUE THREAD

**Issue by JasonBro** [aspnet/templating#446] opened 2018-04-04 22:42 UTC
When I create a new project using the `Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0` Angular template, debugging of typescript in VS2017 is not working.

I can set a breakpoint in Chrome and that works OK, but I can't set a typescript breakpoint in VS2017. The previous version of this template (1.0.417) does allow debugging and the setting of typescript breakpoints in my current configuration of VS2017.

If I include a `debugger;` statement in the typescript, it does break in VS2017, but no code is displayed.

The typescript sources are visible in the Chrome Debugger under webpack:// but are not shown in VS2017.

Can anyone point me in the right direction to investigate this, please?

**Comment by Eilon** [comment] 2018-04-05 17:17
@JasonBro - this sounds like an issue with VS's debugging support, so I recommend logging an issue using VS's built-in "Send feedback / Report a problem" button in the upper-right corner of the VS window. That will ensure that the issue gets routed to the right people in VS and you'll be able to follow the issue's progress there. Unfortunately I don't think there's anything we can do here from within this specific project template.

**Comment by JasonBro** [comment] 2018-04-05 18:16
I think it's more to do with the configuration of the typescript files when used with webpack. I think the map files are not being produced in the way that VS2017 likes them. It's difficult to argue that it's a problem with VS2017's debugging when debugging worked with the previous version of the SPA template, so I would urge you to re-open this and have another look at the problem.

Unfortunately my knowledge of webpack and the typescript configuration is somewhat limited, but I'll play around with it until I find a solution.

**Comment by Eilon** [comment] 2018-04-06 16:40
Understood, thanks for the clarification.

@SteveSandersonMS  - I imagine you have a better sense of these types of issues. If you had to guess, would you think it's more of a VS issue, or we did something odd in the templates?

**Comment by SteveSandersonMS** [comment] 2018-04-16 11:36
It's a duplicate of this: https://github.com/aspnet/JavaScriptServices/issues/1474

Summary: VS and Angular CLI aren't aware of each others' source map formats.

> It's difficult to argue that it's a problem with VS2017's debugging when debugging worked with the previous version of the SPA template

It's specifically because we move to the Angular CLI-based template and hence don't control the source maps format.

**Comment by Stefan-Ilic** [comment] 2018-04-17 17:44
@SteveSandersonMS 

> It's specifically because we move to the Angular CLI-based template and hence don't control the source maps format.

Sorry if I got that wrong, but to me it sounds a bit like "there's nothing we can do about it". Is this issue something you will resolve before releasing .NET Core 2.1 or is it not on the backlog at all?

Don't mean to sound rude or anything, just a quick clarification would be nice.

**Comment by SteveSandersonMS** [comment] 2018-04-17 18:13
@Stefan-Ilic The compatibility between Angular CLI and VS is a matter for Angular CLI and VS, not the template in this repo. So I *hope* they will make this work, but I don't have any inside information about that. It's not something we control in this repo.

**Comment by Eilon** [comment] 2018-04-18 22:07
Closing as dup.

**Closed by Eilon** 2018-04-18 22:07 UTC
Labels: investigate
