### ISSUE TITLE
Adding BrowserAnimationsModule and NoopAnimationsModule causes webpack HMR to duplicate the app element on update

### ISSUE THREAD

**Issue by JimLynn** [aspnet/templating#8] opened 2017-09-13 15:18 UTC
Using exactly the same code as in the angular-animations-example branch, any changes to the app that invokes the webpack hot module replacement results in the previous app element being left behind underneath the newlay added app element. A browser refresh is necessary to get rid of it and test as normal.

This seems to be provoked merely by importing the two AnimationsModules into the browser and server app modules.

Here's my demo of the problem.

https://github.com/JimLynn/AngularCoreWithAnimation/commit/356be71025fff5329265c3aff58c377ec1c9bc89

**Comment by SteveSandersonMS** [comment] 2017-09-28 16:24
Thanks for reporting this.

Closing as duplicate of https://github.com/aspnet/JavaScriptServices/issues/1231, as I am certain that fixing that issue will also resolve this one.

**Closed by SteveSandersonMS** 2017-09-28 16:24 UTC
