### ISSUE TITLE
Visual Studio Professional 2017 15.5.3 update broke HMR

### ISSUE THREAD

**Issue by djdu** [aspnet/templating#232] opened 2018-01-15 13:58 UTC
I'm stuck with the Visual Studio Professional 2017 15.5.3 update. HMR is not starting. It worked fine before I updated the visual studio. 

`An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: Error: Cannot find module "./selectors"`

`AspNetCore._Views_Home_Index_cshtml+<>c__DisplayClass16_0+<<ExecuteAsync>b__0>d.MoveNext() in Index.cshtml
+
    <div id="react-app" asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data=data>Loading...</div>`

Does anyone experiencing this issue? Please help. Thanks.

**Comment by scottaddie** [comment] 2018-01-16 03:17
Duplicate of https://github.com/aspnet/JavaScriptServices/issues/1477

**Closed** 2018-01-19 15:20 UTC
