### ISSUE TITLE
Angular template - BASEURL incorrect to hit weather

### ISSUE THREAD

**Issue by dodegaard** [aspnet/Templating#547] opened 2018-05-31 18:17 UTC
I used the angular template to try out dotnet 2.1 and upon clicking on Fetch Data ran into an error getting to the weather endpoint at http://localhost:54673/api/SampleData/WeatherForecast.  It is using the localhost port of the angular app to reach the API which is being operated at localhost:5000 instead.  Must we have to make a an out of the box implementation change the routing for this base url on the angular side or is there a bug in the beginning template?  Did not see instructions to wire up the api for it to work.  Just let me know the expectation I should have of the magic happening on dotnet run :)  Thanks.

**Comment by mkArtakMSFT** [comment] 2018-06-04 17:23
Thanks for contacting us, @dodegaard.
@javiercn, can you please look into this?

**Comment by javiercn** [comment] 2018-06-04 18:14
@SteveSandersonMS This is all yours

**Comment by mkArtakMSFT** [comment] 2018-06-12 22:39
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment] 2018-08-06 17:52
Reassigning back to @SteveSandersonMS as @ryanbrandenburg got too much stuff on his plate.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment] 2018-08-06 20:16
I couldn't repro it either.

**Comment by mkArtakMSFT** [comment] 2018-08-14 17:41
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by mkArtakMSFT** 2018-08-14 17:41 UTC
Labels: investigate

**Comment by escalonn** [comment] 2018-11-03 20:49
I'm encountering this. Windows 10, `dotnet --version` 2.1.403, `node -v` v10.13.0. Reproduction steps:

```
dotnet new angular
cd ClientApp
npm i
cd ..
dotnet run
```

The `launchSettings.json` is putting the .NET app at 5000, and the Angular server at a different port which seems to be generated by SpaServices since it's not on my disk.

The Angular code gets its base URL for requests in `main.ts` based on the `base href`, `/`, i.e. the server the website is being served from, not the one the API is running on.
