### ISSUE TITLE
Not upgrading to the latest vue version

### ISSUE THREAD

**Issue by bruce-willis** [aspnet/templating#76] opened 2017-10-19 22:09 UTC
### Title
Not installing the last version of [vue](https://github.com/vuejs/vue)

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
1. Download [template repo in dev branch](https://github.com/aspnet/templating) (or create new project via `dotnet new vue`)
2. Go to *src\Microsoft.AspNetCore.SpaTemplates\content\Vue-CSharp* 
3. Open any console you like
4. Run  `npm install` in it
5. After installing run `npm list --depth=0`

### Expected result
Vue and other packages in the latest version [2.5.2 current](https://www.npmjs.com/package/vue)

### Actual result
vue@2.3.4

### Further technical details
If you try manually updated the packages via `npm update --save` and `npm install` project won't build at all

**Comment by Piteryo** [comment] 2017-10-19 22:10
Yeah, the same behaviour

**Comment by Eilon** [comment] 2017-10-20 23:55
@SteveSandersonMS any ideas on this?

**Comment by ctolkien** [comment] 2017-10-24 05:22
Just like to add, that Vue 2.5 has much improved TS support. These templates can hopefully be simplified.

**Comment by Ku4nCheang** [comment] 2017-10-25 04:21
After updated vue to newest version 2.5.2, the client app could not run due to an error
`vue.common.js:573 [Vue warn]: Failed to mount component: template or render function not defined.`

**Comment by ctolkien** [comment] 2017-10-25 04:27
FWIW @Ku4nCheang , I have a "working skeleton / prototype" of the AspNet JS Services working with Vue:

https://github.com/ctolkien/aspnet-vue-webpack-playground

Might give you some tips / and/or a platform to start from.

**Comment by SteveSandersonMS** [comment] 2017-10-31 17:30
We'll update to newer versions of libraries on the next template update, and as part of that will track down and fix any issues caused by breaking changes in those third-party dependencies.

> If you try manually updated the packages via npm update --save and npm install project won't build at all

In the meantime, I'm afraid if there are breaking changes in third-party libraries that cause problems when you upgrade, you'll need to either not upgrade or track down a fix by working with the maintainers of that third-party library.

@Eilon I'd say we can close this. We don't need to have issues tracking the fact that third-party libraries have released updates that we haven't yet ingested. That will be the case very nearly 100% of the time, and we always know we need to update all dependencies eventually.

**Closed** 2017-10-31 19:09 UTC
Labels: investigate
