### ISSUE TITLE
NPM dependencies stop working

### ISSUE THREAD

**Issue by scottaddie** [aspnet/templating#61] opened 2017-10-12 19:44 UTC
Moved from https://github.com/aspnet/Docs/issues/4547. Originally logged by @BlanketGuy.

> I've been having a lot of trouble with the dependencies when creating a project with the Angular template on VS 2017.
First I had to install all the npm packages one by one, and some of them stopped working out of the blue.
Every time I fix something and re-open the project, something else stops working. Anyone else had this problem? How did you solve it?

**Comment by SteveSandersonMS** [comment] 2017-10-19 08:55
We'd really need specific repro steps to be able to do anything with this report. I'm not aware of there being a general issue of "*Every time I fix something and re-open the project, something else stops working*".

@BlanketGuy, could you post repro steps?

**Comment by Eilon** [comment] 2017-11-16 18:15
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-11-16 18:15 UTC
