### ISSUE TITLE
Angular SPA Template has 8 deprecationg warnings

### ISSUE THREAD

**Issue by timheuer** [aspnet/templating#557] opened 2018-06-05 22:39 UTC
File...New ASPNET Core app with Angular.  Build:

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
  npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
  npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
  npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
  npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
  npm WARN deprecated buildmail@4.0.1: This project is unmaintained
  npm WARN deprecated uws@9.14.0: stop using this version

**Comment by mkArtakMSFT** [comment] 2018-06-06 17:30
Thanks for contacting us, @timheuer.
We're closing this as a dupe of https://github.com/aspnet/templating/issues/541, as that'll resolve those warnings.

**Closed by mkArtakMSFT** 2018-06-06 17:30 UTC
