### ISSUE TITLE
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0  when running the template  asp.net core 2.1 + react

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Templating#820] opened 2018-11-03 00:37 UTC
_From @Belka383 on November 2, 2018 22:41_

Hi!
I get an error when running the asp.net core 2.1 project template with react.

My actions in cmd:
1) setx ASPNETCORE_ENVIRONMENT Development /M

My actions in PowerShell:
1) `dotnet new react -o my-new-app`
2) `dotnet build `
3) `dotnet run `
4) open with browser localhost
5) **opening .../fetchdata**

The stack on which I work:
```
SDK for .NET Core (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

NPM:
 Version: 6.4.1

Node: 
 Version: 8.12.8

```

_Copied from original issue: dotnet/templating#1697_

**Comment by mkArtakMSFT** [comment] 2018-11-05 18:37
Thanks for contacting us, @Belka383.
@ryanbrandenburg, can you please look into this?

**Comment by ryanbrandenburg** [comment] 2018-11-08 22:55
@seancpeters I'm attempting to replicate this. In the mean time it would help me to know the following: Does this reproduce with a template created under 2.2? What does the page look like when this happens?

**Comment by seancpeters** [comment] 2018-11-08 22:58
@belka383 - Are you able to provide the info requested in the previous comment from @ryanbrandenburg?

**Comment by ryanbrandenburg** [comment] 2018-11-09 19:38
@Belka383, I wasn't able to replicate, but I think I know the problem anyway. Did you go to `localhost:5001` or to `localhost:$SOMEVALUE` where $SOMEVALUE is `Starting create-react-app server on port $SOMEVALUE...` that you saw in the console output? The value from `Starting create-react-app` is the port for the react server, but for things to work properly you need to get served by the AspNetCore server and have it proxy you to the react app. Otherwise the app will try go to `/api/SampleData` on the REACT server, which will give you an error page (which would start with "<").

I'm going to close this because I'm pretty sure the solution is the above, but if that doesn't solve it for you please feel free to comment again with the info I asked for above (a reproduction app wouldn't hurt either) and I'll re-open and investigate more.

**Closed by ryanbrandenburg** 2018-11-09 19:38 UTC
Labels: investigate

**Comment by Belka383** [comment] 2018-11-24 15:02
Hi!

I create repository: https://github.com/Belka383/wsbareact.git
To repeat the error, you must:

1) git clone this repository;
2) open wsbareact;
3) dotnet build;
4) sd ClientApp and run npm install;
5) npm start;
6) open http://localhost:3000
7) open wsbareact.csproj in Visual Studio 2017 (version 15.9.2);
8) run wsbareact profile (not IIS Express);
9) open http://localhost:3000/fetch-data

When I go to this page, I get an error: 
![image](https://user-images.githubusercontent.com/10748155/48969666-d34e4600-f012-11e8-824e-fe6222c6e693.png)

**Comment by Belka383** [comment] 2018-11-24 15:14
I use port 49917, which is discussed in the issue #1788, but again I get an error:
![image](https://user-images.githubusercontent.com/10748155/48969800-c5012980-f014-11e8-869d-22989b3cf6ae.png)

**Comment by Belka383** [comment] 2018-11-24 15:16
@seancpeters , @ryanbrandenburg -  please give feedback

**Comment by ryanbrandenburg** [comment] 2018-11-26 18:31
@Belka383 it looks like you've made some modifications to the default templates:
```
diff --git a/ClientApp/package.json b/ClientApp/package.json
index fbb568b..f16582d 100644
--- a/ClientApp/package.json
+++ b/ClientApp/package.json
@@ -13,7 +13,7 @@
     "rimraf": "^2.6.2"
   },
   "scripts": {
-    "start": "rimraf ./build && set PORT=49917 && react-scripts start",
+    "start": "rimraf ./build && react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test --env=jsdom",
     "eject": "react-scripts eject"
diff --git a/Properties/launchSettings.json b/Properties/launchSettings.json
index fa17909..eff9e25 100644
--- a/Properties/launchSettings.json
+++ b/Properties/launchSettings.json
@@ -24,8 +24,7 @@
       "launchBrowser": true,
       "environmentVariables": {
         "ASPNETCORE_ENVIRONMENT": "Development"
-      },
-      "applicationUrl": "http://localhost:49917"
+      }
     }
   }
-}
\ No newline at end of file
+}
diff --git a/Startup.cs b/Startup.cs
index 86500ec..e029dd8 100644
--- a/Startup.cs
+++ b/Startup.cs
@@ -60,8 +60,7 @@ namespace wsbareact

                 if (env.IsDevelopment())
                 {
-                    spa.UseProxyToSpaDevelopmentServer("http://localhost:49917");
-                    //spa.UseReactDevelopmentServer(npmScript: "start");
+                    spa.UseReactDevelopmentServer(npmScript: "start");
                 }
             });
         }
```

After reverting those try these steps:
1. git clone this repository;
2. Navigate to wsbareact in the terminal.
3. `dotnet run`
4. open https://localhost:5001/fetch-data

The SpaServices stuff will do all your npm install and npm run, you don't need to manage that yourself (and it's likely to cause problems if you try to).

**Comment by Belka383** [comment] 2018-11-27 20:57
@ryanbrandenburg 
Hi, after the described actions I get the following error:
![image](https://user-images.githubusercontent.com/10748155/49111018-0822fd00-f2a0-11e8-943d-e9d82384398d.png)

**Comment by ryanbrandenburg** [comment] 2018-11-27 21:03
Sounds like your request header has Non-ASCII characters in it. Find out what they are and stop that from happening. Something like Wireshark can be useful for this kind if you're not sure where it might be coming from.

**Comment by Belka383** [comment] 2018-12-01 12:04
@ryanbrandenburg @seancpeters Hi! 
The problem disappeared after I reset the windows... 
Семь бед - один RESET ;-)
