### ISSUE TITLE
MVC template errors on dotnet ef database update

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#53] opened 2017-10-10 01:44 UTC
I found a problem with the MVC 2.0 template, related to running 'dotnet ef database update'.

Repro steps:
>dotnet new mvc -au Individual -uld -f netcoreapp2.0  
>dotnet restore
>dotnet build
>dotnet ef database update

Relevant part of the error:
`System.Data.SqlClient.SqlException (0x80131904): Foreign key 'FK_AspNetUserTokens_AspNetUsers_UserId' references invalid table 'AspNetUsers'.`

Fix:
The problem occurs because the AspNetUserTokens table includes a foreign key to the AspNetUsers table, but the AspNetUsers table is not defined when the AspNetUserTokens table create is attempted. 

To fix the problem, in the file https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Data/Migrations/00000000000000_CreateIdentitySchema.cs 
 move the creation of AspNetUsers table above the creation of AspNetUserTokens

The problem was introduced here:
https://github.com/dotnet/templating/commit/5c7443ff31c4069abee12657bcb35cbc3ac21fa4#diff-442acc416eaa9c694efaa1c5106bce88

**Comment by mkArtakMSFT** [comment] 2018-01-05 23:55
@seancpeters , which OS and what version of the dotnet.exe are you using? You can get the version information running "dotnet --version".

**Comment by seancpeters** [comment] 2018-01-06 00:11
@mkArtakMSFT - I couldn't tell you what version I was running back when this issue was reported - I'm one of the devs for dotnet/templating, so I'm constantly revving / running bleeding edge versions of dotnet new / new3. The specific version of dotnet probably wouldn't matter for this issue, it was a template content problem.

Looking at https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Data/Migrations/00000000000000_CreateIdentitySchema.cs
... it appears the problem is fixed now. I don't see any FK relation between AspNetUsers & AspNetUserTokens anymore.

**Comment by seancpeters** [comment] 2018-01-06 00:20
I think this commit fixed it:
https://github.com/aspnet/templating/commit/5325c65b880db94f5bbcfd1a3912a251f23f4ec1#diff-22cf2c570a91119419f66b3eed95c9b3

**Comment by mkArtakMSFT** [comment] 2018-01-09 19:08
Thanks @seancpeters.
Yes, the issue is fixed already. Closing the bug.

**Closed by mkArtakMSFT** 2018-01-09 19:08 UTC
Labels: 2 - Working, bug, investigate
