### ISSUE TITLE
Test failure: RazorPagesTemplate_NoAuth_Works_NetCore

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Templating#812] opened 2018-10-30 05:51 UTC
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=585423&buildTypeId=Releases_22xPublic_Win2012) with the following error:

```
System.Exception : Process exited with code 1
StdErr: 
StdOut: Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
C:\b\w\e37dd45d8cd1eaf4\.dotnet\x64\sdk\2.2.100-rtm-009571\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj]
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.ObjectPool (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.ObjectPool 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.ObjectPool 2.2.0-rtm-35532 was resolved.
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.Primitives (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.Primitives 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.Primitives 2.2.0-rtm-35532 was resolved.
Build FAILED.
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.ObjectPool (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.ObjectPool 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.ObjectPool 2.2.0-rtm-35532 was resolved.
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.Primitives (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.Primitives 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.Primitives 2.2.0-rtm-35532 was resolved.
    0 Warning(s)
    2 Error(s)
Time Elapsed 00:00:00.67
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.Helpers.AspNetProcess..ctor(ITestOutputHelper output, String workingDirectory, String projectName, String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/AspNetProcess.cs:line 70
   at Templates.Test.TemplateTestBase.StartAspNetProcess(String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 219
   at Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_NoAuthImpl(String targetFrameworkOverride, Boolean noHttps) in /_/test/Templates.Test/RazorPagesTemplateTest.cs:line 57
   at Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_NoAuth_Works_NetCore() in /_/test/Templates.Test/RazorPagesTemplateTest.cs:line 28
------- Stdout: -------
==> C:\b\w\e37dd45d8cd1eaf4\.dotnet\x64\dotnet.exe new razor --debug:custom-hive "C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\.templateengine" [C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531]
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.
Processing post-creation actions...
Running 'dotnet restore' on C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj...
  Restoring packages for C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj...
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.ObjectPool (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.ObjectPool 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.ObjectPool 2.2.0-rtm-35532 was resolved.
C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj : error NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.Primitives (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.Primitives 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.Primitives 2.2.0-rtm-35532 was resolved.
  Generating MSBuild file C:\b\w\e37dd45d8cd1eaf4\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531\obj\AspNet.Template.67ef8b02fe0f453d93e34bc4a379c531.csproj.nuget.g.props.
  Generating MSBuild file C:\b\w\
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC mkArtakMSFT

**Comment by aspnet-hello** [comment] 2018-10-30 05:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment] 2018-10-30 05:51
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585423&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 7:45:36 PM:
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- AngularTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- ReactTemplate_Works_NetCore
- WebApiTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactReduxTemplate_Works_NetCore

**Comment by aspnet-hello** [comment] 2018-10-31 02:31
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 12 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585865&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 4:19:22 PM:
- WebApiTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- AngularTemplate_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- ReactTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- (And 2 more test failures in this build)

**Comment by aspnet-hello** [comment] 2018-11-01 06:41
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 12 failures [with about the same error](http://aspnetci/viewLog.html?buildId=586466&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 8:38:09 PM:
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- EmptyWebTemplate_Works_NetCore
- AngularTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate
- RazorPagesTemplate_NoAuth_Works_NetCore
- WebApiTemplate_Works_NetCore
- (And 2 more test failures in this build)

**Comment by aspnet-hello** [comment] 2018-11-06 22:35
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 13 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588931&buildTypeId=Lite_UniverseTest) on master at 12:10:54 PM:
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- AngularTemplate_Works_NetFramework
- AngularTemplate_NoHttps_Works_NetFramework
- WebApiTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- ReactTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- AngularTemplate_Works_NetCore
- (And 3 more test failures in this build)

**Comment by ryanbrandenburg** [comment] 2018-11-08 20:42
The master problems seem to be caused by Razor. @pranavkm submitted a fix, hopefully it will get through soon.

**Comment by aspnet-hello** [comment] 2018-11-08 23:11
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=590193&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 11:31:28 AM:
- MvcTemplate_NoAuth_Works_NetFramework_ForFSharpTemplate

**Comment by ryanbrandenburg** [comment] 2018-11-09 23:33
Previous failures were fixed by SDK changes/updates, latest failure was an agent problem since resolved.

**Closed by ryanbrandenburg** 2018-11-09 23:33 UTC
Labels: 1 - Ready, Branch:2.2, Branch:master, PRI: 1 - Required, task, test-failure
