### ISSUE TITLE
Broken link in MVC template's privacy banner

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templating#785] opened 2018-10-17 05:11 UTC
The "Learn more" link in the MVC template on the privacy banner goes to https://{public IP}:5001/?page=%2FPrivacy and that is the home page with an ignored query string. Shouldn't link go to https://{public IP}:5001/Home/Privacy?

Found while verifying: aspnet/Release#322

**Comment by mkArtakMSFT** [comment] 2018-10-17 16:39
Thanks @dougbu. This is a dupe of: https://github.com/aspnet/Templating/issues/770

**Closed by mkArtakMSFT** 2018-10-17 16:39 UTC
